<a href="https://colab.research.google.com/github/Arijit1000/email-classification-BERT/blob/main/Email_Classification_using_BERT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf
import tensorflow_hub as hub

In [5]:
!pip install tensorflow_text

     |████████████████████████████████| 4.3 MB 4.9 MB/s 


In [6]:
import tensorflow_text as text

In [7]:
import pandas as pd

df = pd.read_csv("emails.csv")
df.head(5)

Email No.  the  to  ect  and  ...  military  allowing  ff  dry  Prediction
0   Email 1    0   0    1    0  ...         0         0   0    0           0
1   Email 2    8  13   24    6  ...         0         0   1    0           0
2   Email 3    0   0    1    0  ...         0         0   0    0           0
3   Email 4    0   5   22    0  ...         0         0   0    0           0
4   Email 5    7   6   17    1  ...         0         0   1    0           0

[5 rows x 3002 columns]

In [10]:
df.groupby('for').describe()

the                                        ... Prediction                      
      count        mean        std    min     25%  ...        min   25%  50%   75%  max
for                                                ...                                 
0    1133.0    1.612533   2.872574    0.0    0.00  ...        0.0  0.00  0.0  1.00  1.0
1    1387.0    1.940880   3.059906    0.0    0.00  ...        0.0  0.00  0.0  0.00  1.0
2     772.0    4.449482   4.737059    0.0    1.00  ...        0.0  0.00  0.0  1.00  1.0
3     507.0    6.236686   6.338227    0.0    2.00  ...        0.0  0.00  0.0  0.00  1.0
4     331.0    8.069486   7.287474    0.0    3.00  ...        0.0  0.00  0.0  0.00  1.0
5     242.0    9.235537   8.991830    0.0    4.00  ...        0.0  0.00  0.0  0.00  1.0
6     147.0   12.258503   9.541609    1.0    6.00  ...        0.0  0.00  0.0  0.00  1.0
7     129.0   14.697674  10.663610    0.0    6.00  ...        0.0  0.00  0.0  0.00  1.0
8      74.0   14.864865   7.594743    4.0    9.25  ...        0.0  0.00  0.0  0.00  1.0
9      88.0   19.113636  12.888052    2.0    9.00  ...        0.0  0.00  0.0  0.00  1.0
10     58.0   16.172414  11.420416    0.0    9.25  ...        0.0  0.00  0.0  1.00  1.0
11     49.0   21.897959  17.589349    4.0   11.00  ...        0.0  0.00  0.0  1.00  1.0
12     41.0   27.536585  18.156400    3.0   14.00  ...        0.0  0.00  0.0  0.00  1.0
13     31.0   23.741935  13.007607    6.0   14.00  ...        0.0  0.00  0.0  1.00  1.0
14     16.0   19.687500   8.874824    1.0   14.50  ...        0.0  0.00  0.0  0.25  1.0
15     20.0   28.650000  11.314988    1.0   23.00  ...        0.0  0.00  0.0  1.00  1.0
16     15.0   30.333333  14.558584   11.0   17.50  ...        0.0  0.00  0.0  1.00  1.0
17     19.0   35.315789  15.492122    6.0   30.00  ...        0.0  0.00  0.0  1.00  1.0
18     15.0   37.666667  23.530123    1.0   20.00  ...        0.0  0.00  0.0  1.00  1.0
19      9.0   28.333333  13.038405    3.0   24.00  ...        0.0  0.00  0.0  1.00  1.0
20     10.0   49.700000  23.290675   15.0   33.25  ...        0.0  0.00  1.0  1.00  1.0
21     10.0   31.800000  14.838389   13.0   19.00  ...        0.0  0.00  0.0  0.00  1.0
22      4.0   48.750000  13.524669   29.0   45.50  ...        0.0  0.00  0.5  1.00  1.0
23      6.0   60.000000  13.401492   48.0   51.25  ...        0.0  0.25  1.0  1.00  1.0
24      5.0   48.400000  20.057418   28.0   37.00  ...        0.0  0.00  1.0  1.00  1.0
25      4.0   42.000000  18.797163   23.0   29.00  ...        0.0  0.00  0.5  1.00  1.0
26      6.0   55.833333  15.328622   36.0   43.50  ...        0.0  1.00  1.0  1.00  1.0
27      5.0   39.800000  26.892378    2.0   38.00  ...        0.0  0.00  0.0  0.00  1.0
28      6.0   52.500000  22.187835   14.0   46.75  ...        0.0  0.00  0.5  1.00  1.0
29      2.0   53.500000  14.849242   43.0   48.25  ...        0.0  0.25  0.5  0.75  1.0
30      3.0   84.333333  19.502137   62.0   77.50  ...        1.0  1.00  1.0  1.00  1.0
31      4.0   66.250000  45.893899   15.0   33.75  ...        0.0  0.00  0.5  1.00  1.0
32      5.0   68.800000  34.273897   12.0   67.00  ...        0.0  0.00  1.0  1.00  1.0
33      1.0   75.000000        NaN   75.0   75.00  ...        1.0  1.00  1.0  1.00  1.0
34      2.0   52.500000   0.707107   52.0   52.25  ...        1.0  1.00  1.0  1.00  1.0
35      4.0   58.000000  20.314199   40.0   40.75  ...        0.0  0.00  0.0  0.25  1.0
37      4.0  120.750000  63.913353   74.0   74.75  ...        0.0  0.00  0.0  0.00  0.0
38      3.0   81.333333  21.197484   62.0   70.00  ...        0.0  0.50  1.0  1.00  1.0
39      2.0   71.500000  38.890873   44.0   57.75  ...        0.0  0.25  0.5  0.75  1.0
44      1.0  113.000000        NaN  113.0  113.00  ...        0.0  0.00  0.0  0.00  0.0
45      1.0   87.000000        NaN   87.0   87.00  ...        1.0  1.00  1.0  1.00  1.0
47      1.0   53.000000        NaN   53.0   53.00  ...        0.0  0.00  0.0  0.00  0.0

[42 rows x 24000 columns]

In [11]:
df['spam']=df['for'].apply(lambda x: 1 if x=='spam' else 0)
df.head()

Email No.  the  to  ect  and  ...  military  allowing  ff  dry  Prediction
0   Email 1    0   0    1    0  ...         0         0   0    0           0
1   Email 2    8  13   24    6  ...         0         0   1    0           0
2   Email 3    0   0    1    0  ...         0         0   0    0           0
3   Email 4    0   5   22    0  ...         0         0   0    0           0
4   Email 5    7   6   17    1  ...         0         0   1    0           0

[5 rows x 3002 columns]

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['for'],df['spam'], stratify=df['spam'])

In [13]:
X_train.head(4)

1143     3
4862     3
47      13
1137     1
Name: for, dtype: int64

**Now lets import BERT model and get embeding vectors for few sample **

In [14]:
bert_preprocess = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
bert_encoder = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4")

In [15]:
def get_sentence_embeding(sentences):
    preprocessed_text = bert_preprocess(sentences)
    return bert_encoder(preprocessed_text)['pooled_output']

get_sentence_embeding([
    "500$ discount. hurry up", 
    "Bhavin, are you up for a volleybal game tomorrow?"]
)

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.84351707, -0.5132727 , -0.88845736, ..., -0.74748856,
        -0.7531474 ,  0.91964495],
       [-0.8720837 , -0.5054399 , -0.94446677, ..., -0.8584751 ,
        -0.71745366,  0.88082993]], dtype=float32)>

**Get embeding vectors for few sample words. Compare them using cosine similarity**

In [16]:
e = get_sentence_embeding([
    "banana", 
    "grapes",
    "mango",
    "jeff bezos",
    "elon musk",
    "bill gates"
]
)

In [17]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity([e[0]],[e[1]])

array([[0.9911089]], dtype=float32)

Values near to 1 means they are similar. 0 means they are very different. Above you can use comparing "banana" vs "grapes" you get 0.99 similarity as they both are fruits

In [18]:
cosine_similarity([e[3]],[e[4]])

array([[0.98720354]], dtype=float32)


**Build Model**


There are two types of models you can build in tensorflow.

(1) Sequential (2) Functional

So far we have built sequential model. But below we will build functional model. More information on these two is here: https://becominghuman.ai/sequential-vs-functional-model-in-keras-20684f766057

In [19]:
# Bert layers
text_input = tf.keras.layers.Input(shape=(), dtype=tf.string, name='text')
preprocessed_text = bert_preprocess(text_input)
outputs = bert_encoder(preprocessed_text)

# Neural network layers
l = tf.keras.layers.Dropout(0.1, name="dropout")(outputs['pooled_output'])
l = tf.keras.layers.Dense(1, activation='sigmoid', name="output")(l)

# Use inputs and outputs to construct a final model
model = tf.keras.Model(inputs=[text_input], outputs = [l])

In [20]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
text (InputLayer)               [(None,)]            0                                            
__________________________________________________________________________________________________
keras_layer (KerasLayer)        {'input_type_ids': ( 0           text[0][0]                       
__________________________________________________________________________________________________
keras_layer_1 (KerasLayer)      {'sequence_output':  109482241   keras_layer[0][0]                
                                                                 keras_layer[0][1]                
                                                                 keras_layer[0][2]                
______________________________________________________________________________________________

In [21]:
len(X_train)

3879

In [22]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])